=== Batbara/final-web-project-3-1-Talakh/src/main/resources/xml/commandProvider.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mpb.web.tr.by/commandProvider"
           xmlns:tns="http://www.mpb.web.tr.by/commandProvider"
           elementFormDefault="qualified">
    <xs:element name="commandList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="command" type="tns:Command"
                            minOccurs="1"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Command">
        <xs:sequence>
            <xs:element name="commandName" type="xs:string" />
            <xs:element name="className" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Batbara/final-web-project-3-1-Talakh/src/main/resources/xml/commandProvider.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:commandList xmlns:cp="http://www.mpb.web.tr.by/commandProvider"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.mpb.web.tr.by/commandProvider commandProvider.xsd">

    <cp:command scope="admin">
        <cp:commandName>take_user_list</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.admin_command.TakeUserListImpl</cp:className>
    </cp:command>
    <cp:command scope="admin">
        <cp:commandName>ban_user</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.admin_command.BanUserImpl</cp:className>
    </cp:command>
    <cp:command scope="admin">
        <cp:commandName>unban_user</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.admin_command.UnbanUserImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>change_language</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.user_command.ChangeLanguageImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>login</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.user_command.LoginationImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>register</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.user_command.RegistrationImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>logout</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.user_command.LogoutImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>take_account</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.TakeAccountImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>take_movie_list</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.TakeMovieListImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>take_movie</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.TakeMovieImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>take_tv_list</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.TakeTvListImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>take_tv_show</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.TakeTvShowImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>add_user_rate</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.AddUserRateImpl</cp:className>
    </cp:command>
    <cp:command>
        <cp:commandName>add_review</cp:commandName>
        <cp:className>by.tr.web.controller.command.impl.AddReviewImpl</cp:className>
    </cp:command>
</cp:commandList>
