=== Batbara/final-web-project-3-1-Talakh/src/main/resources/xml/tableConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mpb.web.tr.by/tableConfiguration"
           xmlns:tns="http://www.mpb.web.tr.by/tableConfiguration"
           elementFormDefault="qualified">
    <xs:element name="tables">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="table" type="tns:Table"
                            minOccurs="1"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Table">
        <xs:sequence>
            <xs:element name="tableName" type="xs:string" />
            <xs:element name="recordsOnPage" type="xs:positiveInteger" />
            <xs:element name="currentPage" type="xs:positiveInteger" />
            <xs:element name="orderType" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="title"/>
                        <xs:enumeration value="genre"/>
                        <xs:enumeration value="year"/>
                        <xs:enumeration value="seasons"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Batbara/final-web-project-3-1-Talakh/src/main/resources/xml/tableConfiguration.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tc:tables xmlns:tc="http://www.mpb.web.tr.by/tableConfiguration"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.mpb.web.tr.by/tableConfiguration tableConfiguration.xsd">
    <tc:table>
        <tc:tableName>showsTable</tc:tableName>
        <tc:recordsOnPage>25</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
    </tc:table>
    <tc:table>
        <tc:tableName>usersTable</tc:tableName>
        <tc:recordsOnPage>25</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
    </tc:table>
    <tc:table>
        <tc:tableName>moviesTable</tc:tableName>
        <tc:recordsOnPage>5</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
        <tc:orderType>title</tc:orderType>
    </tc:table>
    <tc:table>
        <tc:tableName>tvShowsTable</tc:tableName>
        <tc:recordsOnPage>5</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
        <tc:orderType>title</tc:orderType>
    </tc:table>
    <tc:table>
        <tc:tableName>moderatedReviewsTable</tc:tableName>
        <tc:recordsOnPage>25</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
    </tc:table>
    <tc:table>
        <tc:tableName>showReviewsTable</tc:tableName>
        <tc:recordsOnPage>5</tc:recordsOnPage>
        <tc:currentPage>1</tc:currentPage>
    </tc:table>

</tc:tables>
